name: igdb_api
description: A collection of remote datasources used by our app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  fresh_dio: ^0.4.3
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1



dev_dependencies:
  json_serializable: ^6.9.5  